# file: .github/workflows/show-directory.yml
name: show-directory
# on – определяет события, которые запускают воркфлоу
on: push
jobs:
  # build – произвольно выбранное имя задания
  # их может быть больше одного
  build:
    # операционная система для работы воркфлоу
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v4
        # https://github.com/actions/setup-node
        - uses: actions/setup-node@v4
          with:
            node-version: '18.x'
            cache: 'npm' # ускоряет повторные сборки
        - run: npm ci
        - run: npm test
        - uses: hexlet-components/hello-from-hexlet-action@release

